AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: CD Demo Lambda
Resources:
  CDDemoLambda1:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: LF1
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./indexPhotos
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::308316403373:role/service-role/LF1-role-ambopnx5"
      Environment:
        Variables:
          REGION: us-east-1
  CDDemoLambda2:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: testLex
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./searchPhotos
      Description: "Lambda function for CD Demo"
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::308316403373:role/service-role/testLex-role-uptapox7"
      Environment:
        Variables:
          REGION: us-east-1